services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data:
  
# TODO: Mapear o diret√≥rio de imagens em volume docker

# docker compose up -d


